{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.24"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.24"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.24"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8.jar",
          "size": 4745,
          "sha512": "4af08241b90a6f515faf473433ae9f1773a48cbfe9d3a0c2f78adc7ddc8d574c091523cf5719f2be420d5d2effa1da263abb6791ad6014b7aa580b62171a1b0e",
          "sha256": "6bdd09547e4577a8e702f4ce305bd72e93cd502cd3e133fcc5bdd25463ceb62c",
          "sha1": "1710c1b3a489cb2b4b2712dad615412feeac12e7",
          "md5": "db2aaa9fc92d31c9a86033423442d6e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.24"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.24"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.24"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8.jar",
          "size": 4745,
          "sha512": "4af08241b90a6f515faf473433ae9f1773a48cbfe9d3a0c2f78adc7ddc8d574c091523cf5719f2be420d5d2effa1da263abb6791ad6014b7aa580b62171a1b0e",
          "sha256": "6bdd09547e4577a8e702f4ce305bd72e93cd502cd3e133fcc5bdd25463ceb62c",
          "sha1": "1710c1b3a489cb2b4b2712dad615412feeac12e7",
          "md5": "db2aaa9fc92d31c9a86033423442d6e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8-javadoc.jar",
          "size": 4745,
          "sha512": "4af08241b90a6f515faf473433ae9f1773a48cbfe9d3a0c2f78adc7ddc8d574c091523cf5719f2be420d5d2effa1da263abb6791ad6014b7aa580b62171a1b0e",
          "sha256": "6bdd09547e4577a8e702f4ce305bd72e93cd502cd3e133fcc5bdd25463ceb62c",
          "sha1": "1710c1b3a489cb2b4b2712dad615412feeac12e7",
          "md5": "db2aaa9fc92d31c9a86033423442d6e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8-sources.jar",
          "size": 4745,
          "sha512": "4af08241b90a6f515faf473433ae9f1773a48cbfe9d3a0c2f78adc7ddc8d574c091523cf5719f2be420d5d2effa1da263abb6791ad6014b7aa580b62171a1b0e",
          "sha256": "6bdd09547e4577a8e702f4ce305bd72e93cd502cd3e133fcc5bdd25463ceb62c",
          "sha1": "1710c1b3a489cb2b4b2712dad615412feeac12e7",
          "md5": "db2aaa9fc92d31c9a86033423442d6e0"
        }
      ]
    }
  ]
}
