spring.application.name=bankaccount
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=scott
spring.datasource.password=kosa1004
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=kr.or.oti.bankaccount.dto
mybatis.configuration.map-underscore-to-camel-case=true
