{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-web-server",
    "version": "4.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8.jar",
          "url": "spring-boot-web-server-4.0.8.jar",
          "size": 169240,
          "sha512": "e3d33bb97d54a47bcb2c0b05683717a6203324d43f80cd1216400dcf1b14ab7a31317fe06620bfd33d32e5542ceaa3a770e2eb5c27e50cb1ae1c2bb48842bad1",
          "sha256": "634e37eb6e53cc9d30e54bb8e3969faec289a0cf222e4929446d2af38e6fb6ce",
          "sha1": "f36c87d4a1d46b39ae956baa312cc777cb23856e",
          "md5": "bd0e6a61c437ab324802a5e0ee8f69a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8.jar",
          "url": "spring-boot-web-server-4.0.8.jar",
          "size": 169240,
          "sha512": "e3d33bb97d54a47bcb2c0b05683717a6203324d43f80cd1216400dcf1b14ab7a31317fe06620bfd33d32e5542ceaa3a770e2eb5c27e50cb1ae1c2bb48842bad1",
          "sha256": "634e37eb6e53cc9d30e54bb8e3969faec289a0cf222e4929446d2af38e6fb6ce",
          "sha1": "f36c87d4a1d46b39ae956baa312cc777cb23856e",
          "md5": "bd0e6a61c437ab324802a5e0ee8f69a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8-javadoc.jar",
          "url": "spring-boot-web-server-4.0.8-javadoc.jar",
          "size": 411071,
          "sha512": "f935409a740d919112804c919892eee85ffc90ffc6193ed6f660331bd816bd6e10467c7abf7173de56655c841df91d1ba87cf707ccce800cc08a1d0814e74845",
          "sha256": "e0f7975c72e1c64a6da55bb546e1290a83af6e96ca5e9cf6ed5028fac8bbe561",
          "sha1": "c22b6881afd21ad21cd1e84d453c0956a435e72c",
          "md5": "b35b4e3f97514bd795b262dbb529292d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8-sources.jar",
          "url": "spring-boot-web-server-4.0.8-sources.jar",
          "size": 129311,
          "sha512": "281e0a75f1e853c698872373a8808111edce36ab4731576316c2aef3bc3193eaea5c37572e1a4072c6e7ccdc166ddf3c45d4485aca59c344700a9dafa41bb61d",
          "sha256": "6e9456304c87dcc831fa12f501da76f9d72c91bed1e3dced162fe5b6d0bdbb45",
          "sha1": "4628dc164a6c2e0a070a2bdaa110310f6782137d",
          "md5": "ee11711f1e4b009bc9c77abfd92a6e9b"
        }
      ]
    }
  ]
}
