{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.8"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.8.jar",
          "url": "spring-boot-starter-4.0.8.jar",
          "size": 4768,
          "sha512": "5997a3e233621c4560855ad1eaaf52f23bdd4a8dea830f6aa91f19c974f95364836029f9d1992d3a75a180530248de7c938a097438b2f1e394b4043a65cf74bb",
          "sha256": "f910a1b87c6c39097f5125d96c019135e8dc3bee0322c20f9271e0777aa70ee1",
          "sha1": "79413291d453a1e093b835b3a4f766bbd90ceb09",
          "md5": "e77735a95ca144b393f7b5d9cb1db00c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.8"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.8.jar",
          "url": "spring-boot-starter-4.0.8.jar",
          "size": 4768,
          "sha512": "5997a3e233621c4560855ad1eaaf52f23bdd4a8dea830f6aa91f19c974f95364836029f9d1992d3a75a180530248de7c938a097438b2f1e394b4043a65cf74bb",
          "sha256": "f910a1b87c6c39097f5125d96c019135e8dc3bee0322c20f9271e0777aa70ee1",
          "sha1": "79413291d453a1e093b835b3a4f766bbd90ceb09",
          "md5": "e77735a95ca144b393f7b5d9cb1db00c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.8-javadoc.jar",
          "url": "spring-boot-starter-4.0.8-javadoc.jar",
          "size": 4768,
          "sha512": "5997a3e233621c4560855ad1eaaf52f23bdd4a8dea830f6aa91f19c974f95364836029f9d1992d3a75a180530248de7c938a097438b2f1e394b4043a65cf74bb",
          "sha256": "f910a1b87c6c39097f5125d96c019135e8dc3bee0322c20f9271e0777aa70ee1",
          "sha1": "79413291d453a1e093b835b3a4f766bbd90ceb09",
          "md5": "e77735a95ca144b393f7b5d9cb1db00c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.8-sources.jar",
          "url": "spring-boot-starter-4.0.8-sources.jar",
          "size": 4768,
          "sha512": "5997a3e233621c4560855ad1eaaf52f23bdd4a8dea830f6aa91f19c974f95364836029f9d1992d3a75a180530248de7c938a097438b2f1e394b4043a65cf74bb",
          "sha256": "f910a1b87c6c39097f5125d96c019135e8dc3bee0322c20f9271e0777aa70ee1",
          "sha1": "79413291d453a1e093b835b3a4f766bbd90ceb09",
          "md5": "e77735a95ca144b393f7b5d9cb1db00c"
        }
      ]
    }
  ]
}
